services:
  db:
    image: postgres:16.1-alpine
    container_name: modern_resume_qa_db
    env_file: ".env.qa"
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PORT: ${DB_PORT}

  app:
    build:
      context: .
    container_name: modern_resume_qa_app
    env_file: ".env.qa"
    environment:
      DATABASE_URL: ecto://${DB_USERNAME}:${DB_PASSWORD}@db/${DB_DATABASE}
    ports:
      - ${PHX_PORT}:${PHX_PORT}
    volumes:
      - ./priv/tmp:/app/data
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
