services:
  dev_db:
    image: postgres:16.1-alpine
    container_name: modern_resume_db
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PORT: ${DB_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data

  dev_simplecv_app:
    build:
      context: .
    container_name: simplecv_app_dev
    env_file:
      - ".env.local"
    environment:
      DATABASE_URL: ecto://${DB_USERNAME}:${DB_PASSWORD}@dev_db/${DB_DATABASE}
    ports:
      - ${PHX_PORT}:${PHX_PORT}
    volumes:
      - ./priv/tmp:/app/data
    depends_on:
      - dev_db
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  db_data:
